# Generated by Django 3.2.3 on 2021-05-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210529_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='doors',
        ),
    ]
